### ISSUE TITLE
Update numpy int convert

### ISSUE THREAD

**Issue by nullshii** [theveloped/ThreadTone#10]
Updated from 
```py
return (x.astype(np.int)-1, y.astype(np.int)-1)
```

to
```py
return (x.astype(int)-1, y.astype(int)-1)
```
in line 113

**Comment by nullshii** [comment]
Created pull request in #11

**Comment by buibang1** [comment]
I followed the instructions, but when I run it, it stops in the middle, even though I tried to change the parameters. Please help me.

**Comment by buibang1** [comment]
[+] loaded imgPath.jpg for threading..
[+] image preprocessed for threading..
[+] Computing line 1668 of 2000 total
[+] Image threaded
